### ISSUE TITLE
Consider consolidate git history

### ISSUE THREAD

**Issue by JLHwung** [easyops-cn/next-core#98]
Congratulation on open sourcing `next-core`!

Open sourcing a previously private repo could be risky, the commit history may contain sensitive information, e.g. internal ci config/machine credentials, etc. Consider consolidate the git history before they are leaked.

```
rm -rf .git
git init
git add .
git commit
```

**Comment by weareoutman** [comment]
Hi, thanks for your reminding, appreciate that 🤝 .

We just checked the internal ci config and other parts, fortunately we had kept the most of sensitive messages away from repo since the beginning.

And on the other hand, this repository is a fully front-end project, even though there may be other risks, but we prefer to keep the git history to track the changes to help developers working on it.

**Comment by weareoutman** [comment]
By the way, this is not a fork from internal project, but a single source of truth of our work, we're just moved our development workflow to GitHub from now on 😁 . So the git history will help a lot.
